name: matcha CI

on:
  push:
    paths:
      - './**'
    branches: [ master, develop/*, feature/* ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} running on ${{ env.working-directory }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ${{ env.working-directory }}
      - run: npm install
        working-directory: ${{ env.working-directory }}
      - run: npm run build --if-present
        working-directory: ${{ env.working-directory }}
      - run: npm test
        working-directory: ${{ env.working-directory }}
